import type { SearchSampleType2Row } from './searchSampleType2.types';

export const searchSampleType2Rows: SearchSampleType2Row[] = [
  { REQUEST_NO: 'REQ-2026-001', REQUEST_NAME: '신규 사용자 계정 발급', REQUEST_TYPE: 'STANDARD', STATUS: 'COMPLETED', COMPANY_NAME: 'BaseKit 본사', DEPARTMENT_NAME: '경영지원팀', REQUESTER_NAME: '김하늘', PRIORITY: 'NORMAL', OWNER_NAME: '이운영', REQUESTED_AT: '2026-07-01' },
  { REQUEST_NO: 'REQ-2026-002', REQUEST_NAME: '월 마감 권한 긴급 부여', REQUEST_TYPE: 'URGENT', STATUS: 'IN_PROGRESS', COMPANY_NAME: 'BaseKit 본사', DEPARTMENT_NAME: '재무팀', REQUESTER_NAME: '박정산', PRIORITY: 'HIGH', OWNER_NAME: '최관리', REQUESTED_AT: '2026-07-03' },
  { REQUEST_NO: 'REQ-2026-003', REQUEST_NAME: '메뉴 구조 변경 요청', REQUEST_TYPE: 'CHANGE', STATUS: 'REQUESTED', COMPANY_NAME: 'BaseKit 연구소', DEPARTMENT_NAME: '플랫폼개발팀', REQUESTER_NAME: '윤개발', PRIORITY: 'NORMAL', OWNER_NAME: '이운영', REQUESTED_AT: '2026-07-05' },
  { REQUEST_NO: 'REQ-2026-004', REQUEST_NAME: '퇴직자 계정 잠금', REQUEST_TYPE: 'URGENT', STATUS: 'COMPLETED', COMPANY_NAME: 'BaseKit 물류', DEPARTMENT_NAME: '물류운영팀', REQUESTER_NAME: '정물류', PRIORITY: 'HIGH', OWNER_NAME: '최관리', REQUESTED_AT: '2026-07-08' },
  { REQUEST_NO: 'REQ-2026-005', REQUEST_NAME: '공통코드 신규 등록', REQUEST_TYPE: 'STANDARD', STATUS: 'DRAFT', COMPANY_NAME: 'BaseKit 본사', DEPARTMENT_NAME: '기준정보팀', REQUESTER_NAME: '한기준', PRIORITY: 'LOW', OWNER_NAME: '이운영', REQUESTED_AT: '2026-07-11' },
  { REQUEST_NO: 'REQ-2026-006', REQUEST_NAME: '결재선 변경 적용', REQUEST_TYPE: 'CHANGE', STATUS: 'IN_PROGRESS', COMPANY_NAME: 'BaseKit 연구소', DEPARTMENT_NAME: '품질관리팀', REQUESTER_NAME: '오품질', PRIORITY: 'NORMAL', OWNER_NAME: '최관리', REQUESTED_AT: '2026-07-13' },
  { REQUEST_NO: 'REQ-2026-007', REQUEST_NAME: '협력사 사용자 일괄 등록', REQUEST_TYPE: 'STANDARD', STATUS: 'REQUESTED', COMPANY_NAME: 'BaseKit 물류', DEPARTMENT_NAME: '협력사지원팀', REQUESTER_NAME: '임지원', PRIORITY: 'NORMAL', OWNER_NAME: '이운영', REQUESTED_AT: '2026-07-15' },
  { REQUEST_NO: 'REQ-2026-008', REQUEST_NAME: '시스템 설정값 변경', REQUEST_TYPE: 'CHANGE', STATUS: 'COMPLETED', COMPANY_NAME: 'BaseKit 본사', DEPARTMENT_NAME: '시스템운영팀', REQUESTER_NAME: '서시스템', PRIORITY: 'HIGH', OWNER_NAME: '최관리', REQUESTED_AT: '2026-07-18' },
];
