-- Keep analysis snapshots unchanged; seed the requirement opinion from its latest analysis.
ALTER TABLE BSDRREQ ADD COLUMN DESIGN_OPINION TEXT NOT NULL DEFAULT '';
UPDATE BSDRREQ SET DESIGN_OPINION = COALESCE((
    SELECT ar.DESIGN_OPINION FROM BSDAAREQ ar
    JOIN BSDAANLS a ON a.ANALYSIS_ID = ar.ANALYSIS_ID
    WHERE ar.REQUIREMENT_ID = BSDRREQ.REQUIREMENT_ID
      AND a.PROJECT_ID = BSDRREQ.PROJECT_ID
    ORDER BY a.CREATED_AT DESC, a.ANALYSIS_ID DESC
    LIMIT 1
), '');
