CREATE TABLE BSDRANLS (
    ANALYSIS_ID VARCHAR(50) PRIMARY KEY,
    PROJECT_ID VARCHAR(50) NOT NULL,
    REQUEST_ID VARCHAR(100) NOT NULL,
    ANALYSIS_BASIS VARCHAR(10000) NOT NULL,
    EXECUTED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    REG_DT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT UK_BSDRANLS_REQUEST UNIQUE (PROJECT_ID, REQUEST_ID),
    CONSTRAINT UK_BSDRANLS_PROJECT UNIQUE (PROJECT_ID, ANALYSIS_ID)
);
ALTER TABLE BSDRREQ ADD CONSTRAINT UK_BSDRREQ_PROJECT_ID UNIQUE (PROJECT_ID, REQUIREMENT_ID);
CREATE TABLE BSDRARIT (
    ANALYSIS_ID VARCHAR(50) NOT NULL,
    PROJECT_ID VARCHAR(50) NOT NULL,
    REQUIREMENT_ID VARCHAR(50) NOT NULL,
    ORIGINAL_REASON VARCHAR(10000) NOT NULL,
    REQUIREMENT_MOD_DT TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (ANALYSIS_ID, REQUIREMENT_ID),
    CONSTRAINT FK_BSDRARIT_ANALYSIS FOREIGN KEY (PROJECT_ID, ANALYSIS_ID) REFERENCES BSDRANLS(PROJECT_ID, ANALYSIS_ID),
    CONSTRAINT FK_BSDRARIT_REQUIREMENT FOREIGN KEY (PROJECT_ID, REQUIREMENT_ID) REFERENCES BSDRREQ(PROJECT_ID, REQUIREMENT_ID)
);
CREATE INDEX IX_BSDRANLS_PROJECT ON BSDRANLS(PROJECT_ID, EXECUTED_AT);
CREATE INDEX IX_BSDRARIT_REQUIREMENT ON BSDRARIT(REQUIREMENT_ID);
