ALTER TABLE BSDRREQ ADD COLUMN DISCARDED_YN VARCHAR(1) NOT NULL DEFAULT 'N';
ALTER TABLE BSDRREQ ADD COLUMN REQUIREMENT_REVISION BIGINT NOT NULL DEFAULT 1;
ALTER TABLE BSDRREQ ADD CONSTRAINT CK_BSDRREQ_DISCARDED CHECK (DISCARDED_YN IN ('Y','N'));
CREATE TABLE BSDRRHIS (
 REQUIREMENT_ID VARCHAR(50) NOT NULL REFERENCES BSDRREQ(REQUIREMENT_ID),
 REQUIREMENT_REVISION BIGINT NOT NULL,
 EVENT_TYPE VARCHAR(30) NOT NULL,
 SNAPSHOT TEXT NOT NULL,
 REG_DT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY(REQUIREMENT_ID, REQUIREMENT_REVISION)
);
CREATE TABLE BSDRGRP (
 REQUIREMENT_GROUP_ID VARCHAR(50) PRIMARY KEY,
 PROJECT_ID VARCHAR(50) NOT NULL,
 REQUIREMENT_GROUP_NAME VARCHAR(200) NOT NULL,
 DESCRIPTION TEXT NOT NULL,
 GROUP_STATUS VARCHAR(30) NOT NULL CHECK (GROUP_STATUS IN ('DRAFT','CONFIRMED','REVIEW_REQUIRED')),
 VERSION BIGINT NOT NULL DEFAULT 1,
 REQUEST_ID VARCHAR(100) NOT NULL,
 REQUEST_PAYLOAD TEXT NOT NULL,
 REG_DT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
 MOD_DT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE(PROJECT_ID,REQUIREMENT_GROUP_ID),
 UNIQUE(PROJECT_ID,REQUEST_ID)
);
CREATE TABLE BSDRGRQ (
 REQUIREMENT_GROUP_ID VARCHAR(50) NOT NULL,
 PROJECT_ID VARCHAR(50) NOT NULL,
 REQUIREMENT_ID VARCHAR(50) NOT NULL,
 HUMAN_YN VARCHAR(1) NOT NULL CHECK (HUMAN_YN IN ('Y','N')),
 INCLUSION_REASON TEXT NOT NULL,
 REVIEWED_REVISION BIGINT NOT NULL,
 REVIEWED_SNAPSHOT TEXT NOT NULL,
 PRIMARY KEY(REQUIREMENT_GROUP_ID,REQUIREMENT_ID),
 UNIQUE(PROJECT_ID,REQUIREMENT_GROUP_ID,REQUIREMENT_ID),
 FOREIGN KEY(PROJECT_ID,REQUIREMENT_GROUP_ID) REFERENCES BSDRGRP(PROJECT_ID,REQUIREMENT_GROUP_ID),
 FOREIGN KEY(PROJECT_ID,REQUIREMENT_ID) REFERENCES BSDRREQ(PROJECT_ID,REQUIREMENT_ID)
);
CREATE TABLE BSDRGEVD (
 REQUIREMENT_GROUP_ID VARCHAR(50) NOT NULL,
 PROJECT_ID VARCHAR(50) NOT NULL,
 REQUIREMENT_ID VARCHAR(50) NOT NULL,
 ANALYSIS_ID VARCHAR(50) NOT NULL,
 PRIMARY KEY(REQUIREMENT_GROUP_ID,REQUIREMENT_ID,ANALYSIS_ID),
 FOREIGN KEY(PROJECT_ID,REQUIREMENT_GROUP_ID,REQUIREMENT_ID) REFERENCES BSDRGRQ(PROJECT_ID,REQUIREMENT_GROUP_ID,REQUIREMENT_ID),
 FOREIGN KEY(ANALYSIS_ID,REQUIREMENT_ID) REFERENCES BSDRARIT(ANALYSIS_ID,REQUIREMENT_ID),
 FOREIGN KEY(PROJECT_ID,ANALYSIS_ID) REFERENCES BSDRANLS(PROJECT_ID,ANALYSIS_ID)
);
CREATE INDEX IX_BSDRGRQ_REQ ON BSDRGRQ(REQUIREMENT_ID);
CREATE INDEX IX_BSDRGRP_PROJECT ON BSDRGRP(PROJECT_ID);
