-- Keep historical status and RAW unchanged, while allowing richer execution states.
ALTER TABLE BSDRGANL RENAME COLUMN STATUS TO LEGACY_STATUS;
ALTER TABLE BSDRGANL ALTER COLUMN LEGACY_STATUS DROP NOT NULL;
ALTER TABLE BSDRGANL ADD COLUMN STATUS VARCHAR(30) NOT NULL DEFAULT 'RUNNING';
UPDATE BSDRGANL SET STATUS = LEGACY_STATUS;
ALTER TABLE BSDRGANL ADD CONSTRAINT CK_BSDRGANL_EXECUTION_STATUS CHECK
 (STATUS IN ('RUNNING','SUCCESS','FAILED_TIMEOUT','FAILED_LLM','FAILED_INVALID_JSON','FAILED_TRUNCATED',
             'SUCCEEDED','CALL_FAILED','PARSE_FAILED'));
ALTER TABLE BSDRGANL ADD COLUMN DEADLINE_AT TIMESTAMP WITH TIME ZONE;
ALTER TABLE BSDRGANL ADD COLUMN HTTP_STATUS INTEGER;
ALTER TABLE BSDRGANL ADD COLUMN FINISH_REASON VARCHAR(50);
ALTER TABLE BSDRGANL ADD COLUMN INPUT_TOKENS BIGINT;
ALTER TABLE BSDRGANL ADD COLUMN OUTPUT_TOKENS BIGINT;
ALTER TABLE BSDRGANL ADD COLUMN ELAPSED_MS BIGINT;
CREATE INDEX IX_BSDRGANL_RUNNING ON BSDRGANL(STATUS,DEADLINE_AT);
