CREATE TABLE BSYCDGP (
    CODE_GROUP_ID VARCHAR(50) PRIMARY KEY,
    CODE_GROUP_NAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(500),
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y',
    DEL_YN CHAR(1) NOT NULL DEFAULT 'N',
    REG_DT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    REG_BY VARCHAR(50) NOT NULL,
    MOD_DT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MOD_BY VARCHAR(50) NOT NULL,
    CONSTRAINT CK_BSYCDGP_USE_YN CHECK (USE_YN IN ('Y', 'N')),
    CONSTRAINT CK_BSYCDGP_DEL_YN CHECK (DEL_YN IN ('Y', 'N'))
);

CREATE TABLE BSYCMCD (
    CODE_ID VARCHAR(50) PRIMARY KEY,
    CODE_GROUP_ID VARCHAR(50) NOT NULL,
    CODE VARCHAR(50) NOT NULL,
    CODE_NAME VARCHAR(100) NOT NULL,
    SORT_ORDER INTEGER NOT NULL DEFAULT 0,
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y',
    DEL_YN CHAR(1) NOT NULL DEFAULT 'N',
    REG_DT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    REG_BY VARCHAR(50) NOT NULL,
    MOD_DT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MOD_BY VARCHAR(50) NOT NULL,
    CONSTRAINT UK_BSYCMCD_GROUP_CODE UNIQUE (CODE_GROUP_ID, CODE),
    CONSTRAINT FK_BSYCMCD_CODE_GROUP FOREIGN KEY (CODE_GROUP_ID) REFERENCES BSYCDGP (CODE_GROUP_ID),
    CONSTRAINT CK_BSYCMCD_USE_YN CHECK (USE_YN IN ('Y', 'N')),
    CONSTRAINT CK_BSYCMCD_DEL_YN CHECK (DEL_YN IN ('Y', 'N'))
);

CREATE INDEX IX_BSYCMCD_GROUP_SORT ON BSYCMCD (CODE_GROUP_ID, SORT_ORDER);

INSERT INTO BSYCDGP (CODE_GROUP_ID, CODE_GROUP_NAME, DESCRIPTION, REG_BY, MOD_BY) VALUES
('USER_TYPE_CODE', '사용자유형코드', '사용자의 소속 및 접근 유형을 구분합니다.', 'system', 'system'),
('USER_STATUS_CODE', '사용자상태코드', '사용자 계정의 현재 상태를 구분합니다.', 'system', 'system'),
('ROLE_TYPE_CODE', '권한유형코드', '권한의 사용 목적과 범위를 구분합니다.', 'system', 'system'),
('MENU_TYPE_CODE', '메뉴유형코드', '메뉴의 표시 및 동작 유형을 구분합니다.', 'system', 'system'),
('BOARD_STATUS_CODE', '게시판상태코드', '게시글 또는 게시판의 운영 상태를 구분합니다.', 'system', 'system');

INSERT INTO BSYCMCD (CODE_ID, CODE_GROUP_ID, CODE, CODE_NAME, SORT_ORDER, REG_BY, MOD_BY) VALUES
('USER_TYPE_INTERNAL', 'USER_TYPE_CODE', 'INTERNAL', '내부사용자', 1, 'system', 'system'),
('USER_TYPE_EXTERNAL', 'USER_TYPE_CODE', 'EXTERNAL', '외부사용자', 2, 'system', 'system'),
('USER_TYPE_PARTNER', 'USER_TYPE_CODE', 'PARTNER', '협력사사용자', 3, 'system', 'system'),
('USER_TYPE_SYSTEM', 'USER_TYPE_CODE', 'SYSTEM', '시스템사용자', 4, 'system', 'system'),
('USER_STATUS_ACTIVE', 'USER_STATUS_CODE', 'ACTIVE', '활성', 1, 'system', 'system'),
('USER_STATUS_INACTIVE', 'USER_STATUS_CODE', 'INACTIVE', '비활성', 2, 'system', 'system'),
('USER_STATUS_LOCKED', 'USER_STATUS_CODE', 'LOCKED', '잠김', 3, 'system', 'system'),
('USER_STATUS_EXPIRED', 'USER_STATUS_CODE', 'EXPIRED', '만료', 4, 'system', 'system'),
('ROLE_TYPE_ADMIN', 'ROLE_TYPE_CODE', 'ADMIN', '관리자', 1, 'system', 'system'),
('ROLE_TYPE_OPERATOR', 'ROLE_TYPE_CODE', 'OPERATOR', '운영자', 2, 'system', 'system'),
('ROLE_TYPE_USER', 'ROLE_TYPE_CODE', 'USER', '일반사용자', 3, 'system', 'system'),
('ROLE_TYPE_GUEST', 'ROLE_TYPE_CODE', 'GUEST', '게스트', 4, 'system', 'system'),
('MENU_TYPE_FOLDER', 'MENU_TYPE_CODE', 'FOLDER', '폴더', 1, 'system', 'system'),
('MENU_TYPE_PAGE', 'MENU_TYPE_CODE', 'PAGE', '페이지', 2, 'system', 'system'),
('MENU_TYPE_LINK', 'MENU_TYPE_CODE', 'LINK', '링크', 3, 'system', 'system'),
('MENU_TYPE_HIDDEN', 'MENU_TYPE_CODE', 'HIDDEN', '숨김', 4, 'system', 'system'),
('BOARD_STATUS_USE', 'BOARD_STATUS_CODE', 'USE', '사용', 1, 'system', 'system'),
('BOARD_STATUS_NOT_USE', 'BOARD_STATUS_CODE', 'NOT_USE', '미사용', 2, 'system', 'system'),
('BOARD_STATUS_OPEN', 'BOARD_STATUS_CODE', 'OPEN', '공개', 3, 'system', 'system'),
('BOARD_STATUS_CLOSED', 'BOARD_STATUS_CODE', 'CLOSED', '비공개', 4, 'system', 'system');
