CREATE TABLE BSYCADF (
    ATTRIBUTE_DEF_ID VARCHAR(50) PRIMARY KEY,
    CODE_GROUP_ID VARCHAR(50) NOT NULL,
    ATTRIBUTE_CODE VARCHAR(50) NOT NULL,
    ATTRIBUTE_NAME VARCHAR(100) NOT NULL,
    DATA_TYPE VARCHAR(20) NOT NULL,
    CONTROL_TYPE VARCHAR(30) NOT NULL,
    DISPLAY_TYPE VARCHAR(20) NOT NULL,
    REQUIRED_YN CHAR(1) NOT NULL DEFAULT 'N',
    DEFAULT_VALUE VARCHAR(1000),
    OPTION_SOURCE VARCHAR(200),
    SORT_ORDER INTEGER NOT NULL DEFAULT 0,
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y',
    DEL_YN CHAR(1) NOT NULL DEFAULT 'N',
    REG_DT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    REG_BY VARCHAR(50) NOT NULL,
    MOD_DT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MOD_BY VARCHAR(50) NOT NULL,
    CONSTRAINT UK_BSYCADF_GROUP_ATTRIBUTE UNIQUE (CODE_GROUP_ID, ATTRIBUTE_CODE),
    CONSTRAINT FK_BSYCADF_CODE_GROUP FOREIGN KEY (CODE_GROUP_ID) REFERENCES BSYCDGP (CODE_GROUP_ID),
    CONSTRAINT CK_BSYCADF_DATA_TYPE CHECK (DATA_TYPE IN ('STRING', 'NUMBER', 'BOOLEAN', 'DATE', 'DATETIME')),
    CONSTRAINT CK_BSYCADF_CONTROL_TYPE CHECK (CONTROL_TYPE IN ('TEXT', 'NUMBER', 'SWITCH', 'SELECT', 'DATE_PICKER', 'COLOR_PICKER')),
    CONSTRAINT CK_BSYCADF_DISPLAY_TYPE CHECK (DISPLAY_TYPE IN ('TEXT', 'NUMBER', 'BOOLEAN', 'DATE', 'DATETIME', 'COLOR', 'BADGE')),
    CONSTRAINT CK_BSYCADF_REQUIRED_YN CHECK (REQUIRED_YN IN ('Y', 'N')),
    CONSTRAINT CK_BSYCADF_USE_YN CHECK (USE_YN IN ('Y', 'N')),
    CONSTRAINT CK_BSYCADF_DEL_YN CHECK (DEL_YN IN ('Y', 'N'))
);

CREATE TABLE BSYCAVL (
    CODE_ID VARCHAR(50) NOT NULL,
    ATTRIBUTE_DEF_ID VARCHAR(50) NOT NULL,
    ATTRIBUTE_VALUE VARCHAR(1000),
    DEL_YN CHAR(1) NOT NULL DEFAULT 'N',
    REG_DT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    REG_BY VARCHAR(50) NOT NULL,
    MOD_DT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MOD_BY VARCHAR(50) NOT NULL,
    PRIMARY KEY (CODE_ID, ATTRIBUTE_DEF_ID),
    CONSTRAINT FK_BSYCAVL_CODE FOREIGN KEY (CODE_ID) REFERENCES BSYCMCD (CODE_ID),
    CONSTRAINT FK_BSYCAVL_ATTRIBUTE_DEF FOREIGN KEY (ATTRIBUTE_DEF_ID) REFERENCES BSYCADF (ATTRIBUTE_DEF_ID),
    CONSTRAINT CK_BSYCAVL_DEL_YN CHECK (DEL_YN IN ('Y', 'N'))
);

CREATE INDEX IX_BSYCADF_GROUP_SORT ON BSYCADF (CODE_GROUP_ID, SORT_ORDER);
CREATE INDEX IX_BSYCAVL_ATTRIBUTE_DEF ON BSYCAVL (ATTRIBUTE_DEF_ID);

INSERT INTO BSYCADF (
    ATTRIBUTE_DEF_ID, CODE_GROUP_ID, ATTRIBUTE_CODE, ATTRIBUTE_NAME,
    DATA_TYPE, CONTROL_TYPE, DISPLAY_TYPE, REQUIRED_YN, DEFAULT_VALUE, OPTION_SOURCE,
    SORT_ORDER, REG_BY, MOD_BY
) VALUES
('ATTR_BOARD_COLOR', 'BOARD_STATUS_CODE', 'COLOR', '표시색상', 'STRING', 'COLOR_PICKER', 'COLOR', 'N', '#64748B', NULL, 1, 'system', 'system'),
('ATTR_USER_LOGIN', 'USER_STATUS_CODE', 'LOGIN_ALLOWED', '로그인허용', 'BOOLEAN', 'SWITCH', 'BOOLEAN', 'Y', 'true', NULL, 1, 'system', 'system'),
('ATTR_USER_BADGE', 'USER_STATUS_CODE', 'BADGE_TYPE', '배지유형', 'STRING', 'SELECT', 'BADGE', 'N', NULL, 'CODE_GROUP:BOARD_STATUS_CODE', 2, 'system', 'system');

INSERT INTO BSYCAVL (CODE_ID, ATTRIBUTE_DEF_ID, ATTRIBUTE_VALUE, REG_BY, MOD_BY) VALUES
('BOARD_STATUS_USE', 'ATTR_BOARD_COLOR', '#16A34A', 'system', 'system'),
('BOARD_STATUS_NOT_USE', 'ATTR_BOARD_COLOR', '#94A3B8', 'system', 'system'),
('BOARD_STATUS_OPEN', 'ATTR_BOARD_COLOR', '#2563EB', 'system', 'system'),
('BOARD_STATUS_CLOSED', 'ATTR_BOARD_COLOR', '#DC2626', 'system', 'system'),
('USER_STATUS_ACTIVE', 'ATTR_USER_LOGIN', 'true', 'system', 'system'),
('USER_STATUS_INACTIVE', 'ATTR_USER_LOGIN', 'false', 'system', 'system'),
('USER_STATUS_LOCKED', 'ATTR_USER_LOGIN', 'false', 'system', 'system'),
('USER_STATUS_EXPIRED', 'ATTR_USER_LOGIN', 'false', 'system', 'system'),
('USER_STATUS_ACTIVE', 'ATTR_USER_BADGE', 'OPEN', 'system', 'system'),
('USER_STATUS_INACTIVE', 'ATTR_USER_BADGE', 'NOT_USE', 'system', 'system');
