INSERT INTO BSYCDGP (CODE_GROUP_ID, CODE_GROUP_NAME, DESCRIPTION, REG_BY, MOD_BY)
VALUES ('REQUIREMENT_TYPE_CODE', '요구 유형', '요구사항 접수 유형', 'system', 'system');
INSERT INTO BSYCMCD (CODE_ID, CODE_GROUP_ID, CODE, CODE_NAME, SORT_ORDER, REG_BY, MOD_BY) VALUES
('REQ_TYPE_NEW', 'REQUIREMENT_TYPE_CODE', 'NEW', '신규', 1, 'system', 'system'),
('REQ_TYPE_CHANGE', 'REQUIREMENT_TYPE_CODE', 'CHANGE', '변경', 2, 'system', 'system'),
('REQ_TYPE_IMPROVE', 'REQUIREMENT_TYPE_CODE', 'IMPROVE', '개선', 3, 'system', 'system'),
('REQ_TYPE_DELETE', 'REQUIREMENT_TYPE_CODE', 'DELETE', '삭제', 4, 'system', 'system');

CREATE TABLE BSDRREQ (
    REQUIREMENT_ID VARCHAR(50) PRIMARY KEY,
    PROJECT_ID VARCHAR(50) NOT NULL,
    REQUIREMENT_NAME VARCHAR(200) NOT NULL,
    REQUIREMENT_TYPE_CODE VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(10000) NOT NULL DEFAULT '',
    PROCESS_DESCRIPTION VARCHAR(10000) NOT NULL DEFAULT '',
    STATUS VARCHAR(30) NOT NULL,
    LEGACY_WBS_IDS VARCHAR(2000),
    LEGACY_SCREEN_IDS VARCHAR(2000),
    LEGACY_TABLE_IDS VARCHAR(2000),
    LEGACY_SOURCE_ID VARCHAR(100),
    REG_DT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    REG_BY VARCHAR(50) NOT NULL DEFAULT 'system',
    MOD_DT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MOD_BY VARCHAR(50) NOT NULL DEFAULT 'system',
    CONSTRAINT CK_BSDRREQ_STATUS CHECK (STATUS IN ('DRAFT','IN_PROGRESS','REVIEW','APPROVED')),
    CONSTRAINT UK_BSDRREQ_LEGACY UNIQUE (PROJECT_ID, LEGACY_SOURCE_ID)
);
CREATE INDEX IX_BSDRREQ_PROJECT ON BSDRREQ(PROJECT_ID);

-- MENU_KEY refers to the existing BaseKit menu metadata; there is no separate menu master here.
CREATE TABLE BSDRRMNU (
    REQUIREMENT_ID VARCHAR(50) NOT NULL,
    MENU_KEY VARCHAR(150) NOT NULL,
    PRIMARY KEY (REQUIREMENT_ID, MENU_KEY),
    CONSTRAINT FK_BSDRRMNU_REQ FOREIGN KEY (REQUIREMENT_ID) REFERENCES BSDRREQ(REQUIREMENT_ID)
);

CREATE TABLE BSDRATCH (
    ATTACHMENT_ID VARCHAR(50) PRIMARY KEY,
    REQUIREMENT_ID VARCHAR(50) NOT NULL,
    ORIGINAL_FILE_NAME VARCHAR(255) NOT NULL,
    STORAGE_KEY VARCHAR(100) NOT NULL UNIQUE,
    FILE_TYPE VARCHAR(30) NOT NULL,
    MIME_TYPE VARCHAR(150) NOT NULL,
    FILE_SIZE BIGINT NOT NULL,
    UPLOAD_DT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ANALYSIS_STATUS VARCHAR(30) NOT NULL DEFAULT 'NOT_ANALYZED',
    CONSTRAINT FK_BSDRATCH_REQ FOREIGN KEY (REQUIREMENT_ID) REFERENCES BSDRREQ(REQUIREMENT_ID)
);
CREATE INDEX IX_BSDRATCH_REQ ON BSDRATCH(REQUIREMENT_ID);
