CREATE TABLE BSYMENU (
    MENU_KEY VARCHAR(100) PRIMARY KEY,
    MENU_NAME VARCHAR(100) NOT NULL,
    PARENT_MENU_KEY VARCHAR(100),
    MENU_TYPE_CODE VARCHAR(50) NOT NULL,
    SORT_ORDER INTEGER NOT NULL DEFAULT 0,
    PROGRAM_KEY VARCHAR(100),
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y',
    DEL_YN CHAR(1) NOT NULL DEFAULT 'N',
    REG_DT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    REG_BY VARCHAR(50) NOT NULL,
    MOD_DT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MOD_BY VARCHAR(50) NOT NULL,
    CONSTRAINT FK_BSYMENU_PARENT FOREIGN KEY (PARENT_MENU_KEY) REFERENCES BSYMENU (MENU_KEY),
    CONSTRAINT FK_BSYMENU_PROGRAM FOREIGN KEY (PROGRAM_KEY) REFERENCES BSYPROG (PROGRAM_KEY),
    CONSTRAINT CK_BSYMENU_TYPE CHECK (MENU_TYPE_CODE IN ('FOLDER', 'PAGE')),
    CONSTRAINT CK_BSYMENU_FOLDER_PAGE CHECK (
        (MENU_TYPE_CODE = 'FOLDER' AND PROGRAM_KEY IS NULL)
        OR (MENU_TYPE_CODE = 'PAGE' AND PROGRAM_KEY IS NOT NULL)
    ),
    CONSTRAINT CK_BSYMENU_USE_YN CHECK (USE_YN IN ('Y', 'N')),
    CONSTRAINT CK_BSYMENU_DEL_YN CHECK (DEL_YN IN ('Y', 'N'))
);

CREATE INDEX IX_BSYMENU_PARENT_SORT ON BSYMENU (PARENT_MENU_KEY, SORT_ORDER, MENU_KEY);
CREATE INDEX IX_BSYMENU_PROGRAM ON BSYMENU (PROGRAM_KEY);
