CREATE TABLE BSYBTGP (
    PROGRAM_ID VARCHAR(50) NOT NULL REFERENCES BSYPROG(PROGRAM_ID),
    GROUP_CODE VARCHAR(100) NOT NULL,
    GROUP_TYPE VARCHAR(10) NOT NULL CHECK (GROUP_TYPE IN ('COMMON', 'CUSTOM')),
    GROUP_NAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(500),
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y' CHECK (USE_YN IN ('Y','N')),
    REG_DT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    REG_BY VARCHAR(50) NOT NULL DEFAULT 'system',
    MOD_DT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MOD_BY VARCHAR(50) NOT NULL DEFAULT 'system',
    PRIMARY KEY (PROGRAM_ID, GROUP_CODE)
);
CREATE TABLE BSYENDP (
    ENDPOINT_ID VARCHAR(64) PRIMARY KEY,
    HTTP_METHOD VARCHAR(10) NOT NULL,
    PATH VARCHAR(1000) NOT NULL,
    CONTROLLER_CLASS VARCHAR(500) NOT NULL,
    HANDLER_METHOD VARCHAR(500) NOT NULL,
    COLLECTION_STATUS VARCHAR(10) NOT NULL CHECK (COLLECTION_STATUS IN ('ACTIVE','STALE')),
    REG_DT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    REG_BY VARCHAR(50) NOT NULL DEFAULT 'system',
    MOD_DT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MOD_BY VARCHAR(50) NOT NULL DEFAULT 'system'
);
CREATE TABLE BSYPREP (
    PROGRAM_ID VARCHAR(50) NOT NULL REFERENCES BSYPROG(PROGRAM_ID),
    ENDPOINT_ID VARCHAR(64) NOT NULL REFERENCES BSYENDP(ENDPOINT_ID),
    GROUP_CODE VARCHAR(100),
    REG_DT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    REG_BY VARCHAR(50) NOT NULL DEFAULT 'system',
    MOD_DT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MOD_BY VARCHAR(50) NOT NULL DEFAULT 'system',
    PRIMARY KEY (PROGRAM_ID, ENDPOINT_ID),
    FOREIGN KEY (PROGRAM_ID, GROUP_CODE) REFERENCES BSYBTGP(PROGRAM_ID, GROUP_CODE)
);
CREATE INDEX IX_BSYPREP_ENDPOINT ON BSYPREP(ENDPOINT_ID);
