-- SD requirement analysis, candidate and program generation (V1).
-- No FK to BSDRREQ: snapshots must survive requirement changes/deletion.
CREATE TABLE BSDAANLS (
    ANALYSIS_ID VARCHAR(50) PRIMARY KEY,
    PROJECT_ID VARCHAR(50) NOT NULL,
    REQUEST_ID VARCHAR(100) NOT NULL,
    ACTIVE_REQUEST_ID VARCHAR(100),
    INPUT_VERSION VARCHAR(64) NOT NULL,
    RESULT_VERSION INTEGER NOT NULL DEFAULT 0,
    ANALYSIS_STATUS VARCHAR(30) NOT NULL,
    OVERALL_OPINION TEXT,
    ERROR_CODE VARCHAR(50),
    LAST_RAW_RESPONSE TEXT,
    CREATED_BY VARCHAR(50) NOT NULL DEFAULT 'system',
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT UK_BSDAANLS_REQUEST UNIQUE (PROJECT_ID, REQUEST_ID)
);
CREATE INDEX IX_BSDAANLS_PROJECT ON BSDAANLS(PROJECT_ID, CREATED_AT);

CREATE TABLE BSDAAREQ (
    ANALYSIS_ID VARCHAR(50) NOT NULL,
    REQUIREMENT_ID VARCHAR(50) NOT NULL,
    INPUT_VERSION VARCHAR(64) NOT NULL,
    REQUIREMENT_MOD_DT TIMESTAMP WITH TIME ZONE,
    REQUIREMENT_NAME VARCHAR(300),
    REQUIREMENT_TYPE_CODE VARCHAR(50),
    DESCRIPTION TEXT,
    PROCESS_DESCRIPTION TEXT,
    DESIGN_OPINION TEXT,
    SNAPSHOT_JSON TEXT,
    PRIMARY KEY (ANALYSIS_ID, REQUIREMENT_ID)
);

CREATE TABLE BSDARSLT (
    ANALYSIS_ID VARCHAR(50) NOT NULL,
    RESULT_VERSION INTEGER NOT NULL,
    INPUT_VERSION VARCHAR(64) NOT NULL,
    RAW_RESPONSE TEXT,
    SUMMARY_JSON TEXT,
    BUSINESS_STRUCTURE_JSON TEXT,
    PROCESS_JSON TEXT,
    LAYOUT_JSON TEXT,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ANALYSIS_ID, RESULT_VERSION)
);

CREATE TABLE BSDACAND (
    CANDIDATE_ID VARCHAR(50) PRIMARY KEY,
    ANALYSIS_ID VARCHAR(50) NOT NULL,
    RESULT_VERSION INTEGER NOT NULL,
    TEMP_ID VARCHAR(100),
    PROGRAM_NAME VARCHAR(300),
    PURPOSE TEXT,
    SORT_ORDER INTEGER NOT NULL DEFAULT 0,
    ORIGINAL_JSON TEXT NOT NULL,
    EDITED_JSON TEXT,
    SELECTED_YN CHAR(1) NOT NULL DEFAULT 'N',
    CONFIRMED_YN CHAR(1) NOT NULL DEFAULT 'N',
    GENERATED_YN CHAR(1) NOT NULL DEFAULT 'N',
    GENERATED_PROGRAM_ID VARCHAR(50),
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IX_BSDACAND_ANALYSIS ON BSDACAND(ANALYSIS_ID, RESULT_VERSION);

CREATE TABLE BSDAGREQ (
    GENERATION_REQUEST_ID VARCHAR(100) PRIMARY KEY,
    ANALYSIS_ID VARCHAR(50) NOT NULL,
    RESULT_VERSION INTEGER NOT NULL,
    STATUS VARCHAR(30) NOT NULL,
    CREATED_BY VARCHAR(50) NOT NULL DEFAULT 'system',
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE BSDAGITM (
    GENERATION_REQUEST_ID VARCHAR(100) NOT NULL,
    CANDIDATE_ID VARCHAR(50) NOT NULL,
    STATUS VARCHAR(30) NOT NULL,
    PROGRAM_ID VARCHAR(50),
    ERROR_CODE VARCHAR(50),
    ERROR_MESSAGE VARCHAR(500),
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (GENERATION_REQUEST_ID, CANDIDATE_ID)
);

CREATE TABLE BSDGPROG (
    PROGRAM_ID VARCHAR(50) PRIMARY KEY,
    PROJECT_ID VARCHAR(50) NOT NULL,
    PROGRAM_NAME VARCHAR(300) NOT NULL,
    PURPOSE TEXT NOT NULL,
    LAYOUT_TYPE VARCHAR(30),
    SOURCE_ANALYSIS_ID VARCHAR(50) NOT NULL,
    SOURCE_RESULT_VERSION INTEGER NOT NULL,
    SOURCE_CANDIDATE_ID VARCHAR(50) NOT NULL,
    STATUS VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT UK_BSDACAND UNIQUE (SOURCE_CANDIDATE_ID)
);
CREATE INDEX IX_BSDGPROG_PROJECT ON BSDGPROG(PROJECT_ID);

CREATE TABLE BSDGPREQ (
    PROGRAM_ID VARCHAR(50) NOT NULL,
    REQUIREMENT_ID VARCHAR(50) NOT NULL,
    PRIMARY KEY (PROGRAM_ID, REQUIREMENT_ID)
);

-- Only for existing Project Menus the user explicitly mapped.
CREATE TABLE BSDGPMNU (
    PROGRAM_ID VARCHAR(50) NOT NULL,
    PROJECT_MENU_ID VARCHAR(50) NOT NULL,
    PRIMARY KEY (PROGRAM_ID, PROJECT_MENU_ID)
);
