CREATE TABLE BSDRGCTX (
 REQUIREMENT_GROUP_ID VARCHAR(50) NOT NULL,
 GROUP_VERSION BIGINT NOT NULL,
 REQUEST_JSON TEXT NOT NULL,
 CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY(REQUIREMENT_GROUP_ID,GROUP_VERSION)
);
CREATE TABLE BSDRGANL (
 ANALYSIS_ID VARCHAR(50) PRIMARY KEY,
 REQUIREMENT_GROUP_ID VARCHAR(50) NOT NULL,
 GROUP_VERSION BIGINT NOT NULL,
 REQUEST_ID VARCHAR(100) NOT NULL,
 REQUEST_JSON TEXT NOT NULL,
 RESPONSE_RAW_JSON TEXT,
 MODEL_NAME VARCHAR(200) NOT NULL,
 PROMPT_VERSION VARCHAR(100) NOT NULL,
 STATUS VARCHAR(30) NOT NULL CHECK (STATUS IN ('RUNNING','SUCCEEDED','CALL_FAILED','PARSE_FAILED')),
 ERROR_MESSAGE TEXT,
 CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
 COMPLETED_AT TIMESTAMP WITH TIME ZONE,
 UNIQUE(REQUIREMENT_GROUP_ID,REQUEST_ID),
 FOREIGN KEY(REQUIREMENT_GROUP_ID,GROUP_VERSION) REFERENCES BSDRGCTX(REQUIREMENT_GROUP_ID,GROUP_VERSION)
);
CREATE INDEX IX_BSDRGANL_GROUP ON BSDRGANL(REQUIREMENT_GROUP_ID,CREATED_AT);
