INSERT INTO BSYCDGP (CODE_GROUP_ID, CODE_GROUP_NAME, DESCRIPTION, REG_BY, MOD_BY) VALUES
('REQUIREMENT_STATUS_CODE', '요구사항상태코드', '요구사항 Intake 상태를 구분합니다.', 'system', 'system');

INSERT INTO BSYCMCD (CODE_ID, CODE_GROUP_ID, CODE, CODE_NAME, SORT_ORDER, REG_BY, MOD_BY) VALUES
('REQUIREMENT_STATUS_DRAFT', 'REQUIREMENT_STATUS_CODE', 'DRAFT', '초안', 1, 'system', 'system'),
('REQUIREMENT_STATUS_IN_PROGRESS', 'REQUIREMENT_STATUS_CODE', 'IN_PROGRESS', '진행 중', 2, 'system', 'system'),
('REQUIREMENT_STATUS_REVIEW', 'REQUIREMENT_STATUS_CODE', 'REVIEW', '검토', 3, 'system', 'system'),
('REQUIREMENT_STATUS_APPROVED', 'REQUIREMENT_STATUS_CODE', 'APPROVED', '승인', 4, 'system', 'system');

INSERT INTO BSYCADF (
    ATTRIBUTE_DEF_ID, CODE_GROUP_ID, ATTRIBUTE_CODE, ATTRIBUTE_NAME,
    DATA_TYPE, CONTROL_TYPE, DISPLAY_TYPE, REQUIRED_YN, DEFAULT_VALUE, OPTION_SOURCE,
    SORT_ORDER, REG_BY, MOD_BY
) VALUES
('ATTR_REQUIREMENT_STATUS_COLOR', 'REQUIREMENT_STATUS_CODE', 'COLOR', '표시색상', 'STRING', 'COLOR_PICKER', 'COLOR', 'N', '#64748B', NULL, 1, 'system', 'system');

INSERT INTO BSYCAVL (CODE_ID, ATTRIBUTE_DEF_ID, ATTRIBUTE_VALUE, REG_BY, MOD_BY) VALUES
('REQUIREMENT_STATUS_DRAFT', 'ATTR_REQUIREMENT_STATUS_COLOR', '#64748B', 'system', 'system'),
('REQUIREMENT_STATUS_IN_PROGRESS', 'ATTR_REQUIREMENT_STATUS_COLOR', '#2563EB', 'system', 'system'),
('REQUIREMENT_STATUS_REVIEW', 'ATTR_REQUIREMENT_STATUS_COLOR', '#D97706', 'system', 'system'),
('REQUIREMENT_STATUS_APPROVED', 'ATTR_REQUIREMENT_STATUS_COLOR', '#16A34A', 'system', 'system');
