CREATE TABLE BSDPMSET (
    PROJECT_ID VARCHAR(50) PRIMARY KEY,
    MENU_MANAGEMENT_MODE VARCHAR(10) NOT NULL DEFAULT 'LEVEL',
    REG_DT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    REG_BY VARCHAR(50) NOT NULL DEFAULT 'system',
    MOD_DT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MOD_BY VARCHAR(50) NOT NULL DEFAULT 'system',
    CONSTRAINT CK_BSDPMSET_MODE CHECK (MENU_MANAGEMENT_MODE IN ('LEVEL','SINGLE'))
);

CREATE TABLE BSDPMENU (
    PROJECT_MENU_ID VARCHAR(50) PRIMARY KEY,
    PROJECT_ID VARCHAR(50) NOT NULL,
    MENU_ID VARCHAR(100) NOT NULL,
    MENU_NAME VARCHAR(200) NOT NULL,
    MENU_LEVEL INTEGER,
    LEVEL1_MENU_ID VARCHAR(100),
    SORT_ORDER INTEGER NOT NULL DEFAULT 0,
    REG_DT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    REG_BY VARCHAR(50) NOT NULL DEFAULT 'system',
    MOD_DT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MOD_BY VARCHAR(50) NOT NULL DEFAULT 'system',
    CONSTRAINT UK_BSDPMENU_PROJECT_MENU_ID UNIQUE (PROJECT_ID, MENU_ID)
);
CREATE INDEX IX_BSDPMENU_PROJECT ON BSDPMENU(PROJECT_ID, SORT_ORDER, MENU_ID);

-- New Project Menu relations are kept separate from legacy BSDRRMNU MENU_KEY rows.
CREATE TABLE BSDRRPML (
    REQUIREMENT_ID VARCHAR(50) NOT NULL,
    PROJECT_MENU_ID VARCHAR(50) NOT NULL,
    PRIMARY KEY (REQUIREMENT_ID, PROJECT_MENU_ID),
    CONSTRAINT FK_BSDRRPML_REQ FOREIGN KEY (REQUIREMENT_ID) REFERENCES BSDRREQ(REQUIREMENT_ID) ON DELETE CASCADE,
    CONSTRAINT FK_BSDRRPML_MENU FOREIGN KEY (PROJECT_MENU_ID) REFERENCES BSDPMENU(PROJECT_MENU_ID)
);
CREATE INDEX IX_BSDRRPML_MENU ON BSDRRPML(PROJECT_MENU_ID);
